name: nippon_calendar
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  syncfusion_flutter_calendar: ^24.1.44
  nholiday_jp: ^1.0.2
  flutter_localization: ^0.2.0
  flutter_local_notifications:
  timezone:
  firebase_core:
  firebase_messaging: ^14.7.10
  flutter_timezone:
  path_provider:
  device_info_plus: ^9.1.1 
  http: ^1.1.2
  image: ^4.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

